version: "3.8"
services:
    api:
        build: .
        image: aviegener/rappi-prediction-api
        container_name: rappi-prediction-api
        ports: 
            - "8000:8000"

    mongo:
        image: mongo
        container_name: rappi-mongo-db
        ports: 
            - "27017:27017"
        volumes:
            - dbdata:/data/db
    
volumes:
    dbdata: